export const SET_AUTH_USER = "SET_AUTH_USER";

export const PROGRESS_SAVING = "PROGRESS_SAVING";
export const PROGRESS_LOADING = "PROGRESS_LOADING";
export const PROGRESS_SAVED = "PROGRESS_SAVED";
export const PROGRESS_LOADED = "PROGRESS_LOADED";

export const RECEIVE_QUESTIONS = "RECEIVE_QUESTIONS";
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const ADD_QUESTION = "ADD_QUESTION";

export const RECEIVE_USERS = "RECEIVE_USERS";
